"""add next_maintenance_date

Revision ID: 10fbff23029f
Revises: 142051adc995
Create Date: 2026-07-03 11:49:12.984394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fbff23029f'
down_revision = '142051adc995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_maintenance_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_column('next_maintenance_date')

    # ### end Alembic commands ###
