"""Initial migration

Revision ID: 142051adc995
Revises: 
Create Date: 2026-07-01 11:26:00.910823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142051adc995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unique_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_table('equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('installation_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('maintenance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('installation_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('engineer', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours_planned', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_events')
    op.drop_table('equipment')
    op.drop_table('installations')
    op.drop_table('locations')
    op.drop_table('clients')
    # ### end Alembic commands ###
