"""add next_maintenance_date and photo_url

Revision ID: 323a3c7ba0ad
Revises: 10fbff23029f
Create Date: 2026-07-03 12:25:43.011716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323a3c7ba0ad'
down_revision = '10fbff23029f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
